# Generated by Django 5.2.1 on 2025-05-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklending',
            name='borrower_email',
        ),
        migrations.RemoveField(
            model_name='booklending',
            name='borrower_name',
        ),
        migrations.AddField(
            model_name='booklending',
            name='borrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_lendings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
