# Generated by Django 5.2.1 on 2025-05-17 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_remove_booklending_borrower_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreservation',
            name='reserver_email',
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='reserver_name',
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='reserver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_reservations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
