# Generated by Django 5.2.1 on 2025-05-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_remove_bookreservation_reserver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklending',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booklending',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
