# Generated by Django 5.2.1 on 2025-05-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_booklending_daily_price_booklending_penalty_amount'),
        ('library', '0005_alter_book_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreservation',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reservations', to='library.bookcopy'),
        ),
    ]
